const ACCESS_TOKEN = 'ACCESS_TOKEN';
const RESERVATION_PREVIEW = 'RESERVATION_PREVIEW';
const USER_ID = 'USER_ID';
const USER_TYPE = 'USER_TYPE';
const USER_TOKEN_TTL = 'USER_TOKEN_TTL';

export { ACCESS_TOKEN, USER_ID, USER_TOKEN_TTL, USER_TYPE, RESERVATION_PREVIEW };
